version: 2.0

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/android:api-28

    steps:
      - checkout
      
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Run tests
          command: ./gradlew lintDebug testDebugUnitTest

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
